categories:
  -
    id: "toc"
    name: "Guides & SDKs"
    description: "References and documentation"
  -
    id: "product"
    name: "Product"
    description: "Learn how to use the key features of Auth0"
    links:
      -
        name: "Overview"
        icon: "icon-budicon-121"
        description: "What is Auth0 and how can it help you build applications."
        href: "/overview"
      -
        name: "Applications"
        icon: "icon-budicon-349"
        description: "Understanding an application in the context of Auth0."
        href: "/applications"
      -
        name: "Rules"
        icon: "icon-budicon-173"
        description: "Extend and enhance Auth0 with your custom logic."
        href: "/rules"
      -
        name: "Identity Providers"
        icon: "icon-budicon-297"
        description: "Discover all the of identity providers Auth0 supports."
        href: "/identityproviders"
      -
        name: "Single Sign-On"
        icon: "icon-budicon-170"
        description: "Provide a better user experience with single sign-on."
        href: "/sso/single-sign-on"
      -
        name: "User Profile"
        icon: "icon-budicon-289"
        description: "Learn how to use and add metadata to the user profile."
        href: "/user-profile"
      -
        name: "Multifactor Authentication"
        icon: "icon-budicon-243"
        description: "Add additional security with a second factor of authentication."
        href: "/mfa"
      -
        name: "Passwordless Authentication"
        icon: "icon-budicon-499"
        description: "Authenticate users without a password using SMS, Email, or TouchID."
        href: "/connections/passwordless"
      -
        name: "Auth0 Appliance"
        icon: "icon-budicon-359"
        description: "Deploy Auth0 to your own cloud or datacenter."
        href: "/appliance"
  -
    id: "api"
    name: "API"
    description: "The core Auth0 APIs for Authentication and Management"
    sections:
      auth-endpoints:
        name: "Authentication API"
        description: "Perform enterprise authentication or OpenID operations using these APIs."
        href: "/auth-api/"
      explorer:
        name: "Management API"
        description: "Perform administrative tasks such as creating accounts or changing settings with the Management API."
        href: "/api/v2/"
      announcements:
        name: "Releases & Updates"
        links:
          -
            name: "Platform Releases"
            href: "https://releases.auth0.com"
          -
            name: "Content & SDK Updates"
            href: "/updates"
  -
    id: "platform"
    name: "Platforms"
    description: ""
    links:
      -
        name: "Web Developers"
        href: "/"
      -
        name: "Single Page App Developers"
        href: "/"
      -
        name: "API Developers"
        href: "/"
      -
        name: "Mobile Developers"
        href: "/"

  -
    id: "sdk"
    name: "SDKs"
    description: "Explore content by language and platform"
    links:
      -
        name: "Node SDK"
        slug: "node"
        href: "/server-platforms/nodejs"
      -
        name: "Javascript SDK"
        slug: "vanillajs"
        href: "/client-platforms/vanillajs"
      -
        name: "iOS SDK"
        slug: "ios"
        href: "/native-platforms/ios-objc"
      -
        name: "Android SDK"
        slug: "android"
        href: "/native-platforms/android"
      -
        name: "Ruby SDK"
        slug: "ruby"
        href: "/server-apis/ruby"
      -
        name: ".NET SDK"
        slug: "net"
        href: "/server-platforms/aspnet-owin"
      -
        name: "Python SDK"
        slug: "python"
        href: "/server-platforms/python"
      -
        name: "Java SDK"
        slug: "java"
        href: "/server-platforms/java"
  -
    id: "ui-component"
    name: "UI Components"
    links:
      -
        name: "Lock for Web"
        description: "Auth UI for your web app"
        href: "/libraries/lock"
      -
        name: "Lock for iOS"
        description: "Native iOS Authentication UI"
        href: "/libraries/lock-ios"
      -
        name: "Lock for Android"
        description: "Native Android Authentication UI"
        href: "/libraries/lock-android"
  -
    id: "web-frameworks"
    name: "Web Frameworks"
    description: ""
    links:
      -
        name: "AngularJS"
        href: "/"
      -
        name: "EmberJS"
        href: "/"
      -
        name: "React"
        href: "/"
  -
    id: "how-to"
    name: "Guides"
    description: "Learn how to get the most out of Auth0"
    links:
      -
        name: "Refresh Tokens"
        icon: "icon-budicon-754"
        href: "/refresh-token"
        description: "How to securely renew id tokens within your apps."
      -
        name: "Importing and Migrating Users to Auth0"
        icon: "icon-budicon-754"
        href: "/connections/database/migrating"
        description: "Import users from existing applications into Auth0."
      -
        name: "Customizing Sign Up Forms"
        icon: "icon-budicon-754"
        href: "/custom-signup"
        description: "Deliver a customized signup experience to your users."
      -
        name: "Linking Accounts"
        icon: "icon-budicon-754"
        href: "/link-accounts"
        description: "Unify a single user's identity using different identity providers."
      -
        name: "Logout"
        icon: "icon-budicon-754"
        href: "/logout"
        description: "Learn about clearing sso cookies and other logout operations."
      -
        name: "Connecting Active Directory"
        icon: "icon-budicon-754"
        href: "/connections/enterprise/active-directory"
        description: "Learn how to use Auth0 with Active Directory."
      -
        name: "Using and Configuring SAML"
        icon: "icon-budicon-754"
        href: "/saml-configuration"
        description: "Get your SAML application set up for authentication and single sign-on."
      -
        name: "Custom Password Strength"
        icon: "icon-budicon-754"
        href: "/password-strength"
        description: "Set the password strength to enhance your app's security."
      -
        name: "Configure Emails"
        icon: "icon-budicon-778"
        href: "/email"
        description: "Learn how to configure the account management emails that Auth0 sends."
  -
    id: "start"
    name: "Getting Started"
    links:
      -
        name: "Auth0 in 5 minutes"
        href: "/"
      -
        name: "Auth0 in 30 minutes"
        href: "/"
      -
        name: "Quickstart Tutorials"
        href: "/quickstart"
      -
        name: "Best Practices"
        href: "/"
